#+TITLE: csvs-sh
#+OPTIONS: toc:nil

Query and edit csvs data in human-readable formats with your favorite text editor; merge, split, and clean csvs databases. Currently supported formats for editing: [[https://github.com/fetsorn/biorg-spec][biorg]].

* API
break-biorg - Reads a biorg compilation, breaks each node, outputs path to a temporary metadir

build-biorg - Reads a stream of datum_uuid,datum pairs from stdin, looks up props in metadir, outputs biorg

gc - Deduplicates, sorts, and removes garbage from metadir

lookup - Finds a value corresponding to UUID in metadir

mdirsync - Syncs metadir with a biorg file

merge - merges one metadir into another

unescape - removes JSON escapes from a string

* Setup
#+begin_src sh
# enter a dev shell
nix develop
# or install bash_unit, coreutils, file, gawk, jq, moreutils, parallel, ripgrep

# run tests
bash_unit tests/*
#+end_src

* More csvs projects
[[https://github.com/fetsorn/csvs-spec][csvs-spec]] - format description

[[https://github.com/fetsorn/qualia][qualia]] - Web UI and desktop app. Tell the story of your own data.

[[https://github.com/fetsorn/csvs-js][csvs-js]] - WASM/JS implementation. Serverless CRUD.
