#!/bin/bash

script="../scripts/lookup"
uuid1="8260502525153a8775ecb052f41e4e908aba4c94b07ef90263fff77195392704"
value1="value1"
tests_index=$(mktemp)

code() {
    printf "%s,%s" "$uuid1" "$value1" > $tests_index
}

test_lookup_fails_without_args() {
    assert_fail $script
}
test_lookup_fails_with_one_arg() {
    assert_fail $script $(mktemp)
}
test_lookup_succeeds_with_two_args() {
    code
    assert "$script $tests_index $uuid1"
}
test_lookup_prints_value() {
    code
    assert_equals "$value1" $($script $tests_index $uuid1) "should equal value1"
}
