#!/bin/bash

usage () {
  printf 1>&2 "%s\n" "Usage: $0

  csvs - general-purpose plain-text database

  SUBCOMMANDS:
  build    Read \"datum_uuid,datum\" pairs, output biorg
  break    Read biorg, break each node, output path to a temporary metadir
  cache    Read paths from stdin, break, output path to a temporary metadir
  gc       Deduplicate, sort, and remove garbage from metadir
  sync     Sync metadir with a biorg file
  merge    Merge one metadir into another
"
}

SCRIPTS="${BASH_SOURCE%/*}"
if [[ ! -d "$SCRIPTS" ]]; then SCRIPTS="$PWD"; fi

case "$1" in
build)
  shift
  bash "$SCRIPTS/build-biorg" "$@";;
"break")
  shift
  gawk -f "$SCRIPTS/break-biorg" -v CONFIG="$PWD/metadir.json" "$@";;
cache)
  shift
  bash "$SCRIPTS/break-fs" "$@";;
gc)
  shift
  bash "$SCRIPTS/gc" "$@";;
merge)
  shift
  bash "$SCRIPTS/merge" "$@";;
sync)
  shift
  bash "$SCRIPTS/mdirsync" "$@";;
*)
  usage;;
esac
