#!/bin/bash

if [ $# -ne 2 ]; then
  printf 1>&2 "%s\n" "Usage: $0 FILENAME UUID

  Finds a value corresponding to UUID in FILENAME

  EXAMPLE:
    $0 metadir/filepath/index.csv 8260502525153a8775ecb052f41e4e908aba4c94b07ef90263fff77195392704"
  exit 3
fi

filename="$1"
uuid="$2"

# printf 1>&2 "lookup: %s, %s\n" "$filename" "$uuid"
cat "$filename" | grep -o "^$uuid,.*" | sed "s/^$uuid,//" | head -n 1
